### PR TITLE
Stop `TextInput` `keydown` event propagation 

### LINKED ISSUE #400: Submitting search triggers validation on faucet page
When I press <kbd>enter</kbd> in the search input, it triggers a validation on the faucet page.

https://user-images.githubusercontent.com/158411/191478628-92f8d272-4a35-46c0-a2a9-73511ca33a7f.mov

### PR DESCRIPTION
**Pull request by grayliquid**
Fixes #400

### CODE REVIEW

**Comment by sebastinez** [comment]
Hey @grayliquid,

First let me thank you for your PR.
@rudolfs what do you think about stopping the event propagation with `on:keydown|stopPropagation` in the `TextInput` element?

**Comment by grayliquid** [comment]
6ubq4z

ty both

**Comment by rudolfs** [comment]
@grayliquid very nice! Could you squash the commits and format the commit message so it's consistent with our style (i.e drop the prefix)? Would be also nice if you could set up ssh/gpg signing, so that your commits show up verified, not a hard requirement tho.

**Comment by rudolfs** [comment]
Nice! Could you rebase it one last time? 😅

**Comment by rudolfs** [comment]
Thanks for the contribution! 👏

**Comment by grayliquid** [comment]
(sry for causing so much review work with a 1 line change PR :sweat_smile:)

**Comment by rudolfs** [comment]
No worries, it's just the first time onboarding setup. Next one is going to be smoother :)

**Pull request merged**
