### PR TITLE
Make modal corners rounded

### PR DESCRIPTION
**Pull request by rudolfs**
All other elements in the app have rounded corners:

Screenshot 2022-09-13 at 12 16 40
Screenshot 2022-09-13 at 12 16 44
Screenshot 2022-09-13 at 12 16 47
Screenshot 2022-09-13 at 12 16 56
Screenshot 2022-09-13 at 12 17 06
Screenshot 2022-09-13 at 12 17 14
Screenshot 2022-09-13 at 12 17 19

It feels weird to me that the modal is the only element that has sharp corners.

Screenshot 2022-09-13 at 12 18 08

Thus I propose to make them consistent with the rest of the design:
Screenshot 2022-09-13 at 12 14 39
Screenshot 2022-09-13 at 12 14 45
Screenshot 2022-09-13 at 12 14 53
Screenshot 2022-09-13 at 12 15 15

### CODE REVIEW

**Review by brandonhaslegs — APPROVED** [review]
Looks good. Only think maybe we should make the two border radii css variables?

**Comment by rudolfs** [comment]
> Looks good. Only think maybe we should make the two border radii css variables?

Good point: 7916f142f54abcff1224cd4fb540433b0ff14d52  450a8dea13737f64578af7de57479146f154ae24

**Comment by cloudhead** [comment]
Hmm but the window view area itself is not rounded :thinking:

**Comment by rudolfs** [comment]
> Hmm but the window view area itself is not rounded 🤔

On my machine it is 😅 

mymachine

**Comment by brandonhaslegs** [comment]
> Hmm but the window view area itself is not rounded :thinking: 

This is a joke right?

**Comment by cloudhead** [comment]
Though:
image

**Comment by rudolfs** [comment]
> Though: image

lol, u got me

**Comment by cloudhead** [comment]
Not a fan of this change tbh, looks weird to me.

**Comment by rudolfs** [comment]
> Not a fan of this change tbh, looks weird to me.

No biggie 🤷

**Pull request closed without merging**
