### PR TITLE
Bump node version to 18.12.0 LTS

### PR DESCRIPTION
**Pull request by rudolfs**
Also use the same node version consistently across local dev, CI and production environments.

### CODE REVIEW

**Review by cloudhead — APPROVED** [review]
There used to be an issue with later node versions that made us go back to an earlier one, but @sebastinez will maybe remember more.

**Comment by rudolfs** [comment]
> There used to be an issue with later node versions that made us go back to an earlier one, but @sebastinez will maybe remember more.

IIRC it was Cypress, which we upgraded recently, so that requirement is no more.

**Comment by rudolfs** [comment]
TODO:
  - [ ] fix warning
Screenshot 2022-10-04 at 08 43 10

- [ ] fix go-to-definition stopped working
- [ ] test more extensively

**Comment by rudolfs** [comment]
So turns out `coc-svelte` is unmaintained. Made [a fork and fixed the issues](https://github.com/rudolfs/coc-svelte) with it not being compatible with node 18.

Here are my `init.vim` changes:
```diff
+Plug 'rudolfs/coc-svelte', {'do': 'yarn install --frozen-lockfile'}

-let g:coc_global_extensions = ['coc-tsserver', 'coc-tslint-plugin', 'coc-svelte', 'coc-rust-analyzer', 'coc-json', 'coc-prettier', 'coc-eslint']
+let g:coc_global_extensions = ['coc-tsserver', 'coc-tslint-plugin', 'coc-rust-analyzer', 'coc-json', 'coc-prettier', 'coc-eslint']
```

**Review by sebastinez — APPROVED** [review]
🎉

**Pull request merged**
