### PR TITLE
New elevation variable

### LINKED ISSUE #507: Explore introducing higher contrast to the UI
I think this would improve the contrast of the UI a lot. Right now it feels a bit washed out, but I think this would do a lot. Need to do a fuller design exploration on it though. And not sure how it would translate to dark mode.

image

### PR DESCRIPTION
**Pull request by brandonhaslegs**
Adds new elevation variable which adds better contrast in light mode closes #507 

Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>

image
image
image
image
image

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
This problem didn't really exist in dark mode, but I still added a slightly lighter value for this new `elevation` variable in dark mode. Could just change it to match the `background` value though…

**Comment by cloudhead** [comment]
Looks good to me!

Can you format your commit message according to https://github.com/radicle-dev/radicle-interface/blob/master/CONTRIBUTING.md#writing-git-commit-messages ? Mainly the summary shouldn't be longer than 50 chars otherwise it gets cropped.

**Review by rudolfs — COMMENTED** [review]
- The `package-lock.json` file should not be committed in this case.
- Could we call it `--color-background-1` instead of `--color-elevation-1`? We use elevations for box-shadows, and they live in `elevations.css`.

Screenshot 2023-02-01 at 10 05 38
Screenshot 2023-02-01 at 10 05 44
Screenshot 2023-02-01 at 10 05 48

**Review by rudolfs — COMMENTED** [review]
👍

**Pull request merged**
