### PR TITLE
Add source information to profile information

### PR DESCRIPTION
**Pull request by sebastinez**
This PR adds the source origin to each property of the profile of each user.

This should allow us to eg. link in case of ENS to the registration form from the user view, and in case of IDX to the self.id app.
I can see that in the future with other identity providers this could help us also in other use cases.

Feel free to provide feedback, did test the PR and run all the checks

### CODE REVIEW

**Comment by cloudhead** [comment]
Hmmm, this works, but I would have thought that a much simpler solution would just be to have a `url()` method on `Profile` that returns the right thing depending on whether it's ENS or IDX. The current code assumes that the name can come from one place and the avatar from a different places, but it's either/or, since we don't merge metadata currently.

**Comment by sebastinez** [comment]
> Hmmm, this works, but I would have thought that a much simpler solution would just be to have a `url()` method on `Profile` that returns the right thing depending on whether it's ENS or IDX. The current code assumes that the name can come from one place and the avatar from a different places, but it's either/or, since we don't merge metadata currently.

Okay, yeah this would be much simpler. I see a benefit for users in loading something thats available on IDX but not on ENS.
But we could start using a `url()` method and see how to merge metadata in the future.

**Comment by cloudhead** [comment]
> > Hmmm, this works, but I would have thought that a much simpler solution would just be to have a `url()` method on `Profile` that returns the right thing depending on whether it's ENS or IDX. The current code assumes that the name can come from one place and the avatar from a different places, but it's either/or, since we don't merge metadata currently.
> 
> Okay, yeah this would be much simpler. I see a benefit for users in loading something thats available on IDX but not on ENS.
> But we could start using a `url()` method and see how to merge metadata in the future.

Yeah, indeed, though maybe also a bit confusing to have a profile patched together from multiple sources :thinking:

**Comment by sebastinez** [comment]
Will open this PR again on a separate branch and with the `url()` method

**Pull request closed without merging**
