### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by rudolfs**
To keep us up-to-date. This also updates transitive dependencies.

### CODE REVIEW

**Comment by sebastinez** [comment]
It seems that the build smoke test is failing because of https://github.com/microsoft/playwright/pull/21106

**Comment by rudolfs** [comment]
> It seems that the build smoke test is failing because of [microsoft/playwright#21106](https://github.com/microsoft/playwright/pull/21106)

Oh, good catch. I was trying to figure this out yesterday, but couldn't find what was wrong with it.

**Comment by rudolfs** [comment]
There seems to be a regression in FF: https://github.com/microsoft/playwright/issues/21145.

**Comment by sebastinez** [comment]
> There seems to be a regression in FF: [microsoft/playwright#21145](https://github.com/microsoft/playwright/issues/21145).

Maybe we should exclude playwright from this update? Since there are some other dependencies that are either major updates or at least minor ones.

**Comment by rudolfs** [comment]
> Maybe we should exclude playwright from this update? Since there are some other dependencies that are either major updates or at least minor ones.

Yeah, can do.

**Review by sebastinez — APPROVED** [review]
LGTM, seems to work nicely

**Comment by rudolfs** [comment]
Hm, on second thought, I think this won't work, because the problem seems to be with the newer firefox browser version. And we don't have a way to not update the browsers when bumping deps. So we either disable the firefox tests or wait for playwright to fix it on their end.

**Comment by sebastinez** [comment]
> Hm, on second thought, I think this won't work, because the problem seems to be with the newer firefox browser version. And we don't have a way to not update the browsers when bumping deps.

So we are kinda vendor locked in by Microsoft :sweat_smile:

**Pull request merged**
