### PR TITLE
Update border radius

### LINKED ISSUE #274: Make border-radii more unified
There

0px
image

4px
image
image
image

8px
image

16px
image

50px
image

I'd recommend making everything just `1em`. Feels like a nice friendly size. You could also keep the fully-rounded buttons and "chips" in the UI, they'd fit with the 1rem border radius.

### LINKED ISSUE #276: Border radius on Codeblocks is not unified
Top is 4px
image

Bottom is 0px
image

### PR DESCRIPTION
**Pull request by brandonhaslegs**
- added 3 new css variables for border radius
  - small
  - normal
  - fully-round (not 50%, which results in oval shapes)
- replaced all manual border-radius numbers with css variables

Fixes #274 
Fixes #276

Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>

### CODE REVIEW

**Comment by sebastinez** [comment]
Hey @brandonhaslegs thanks for the PRs! We try to signoff our work by adding a sign-off message at the end of the commit message `Signed-off-by:C O Mitter \ <committer@example.com>` you can add this manually or by doing `git commit ... -S`

**Comment by brandonhaslegs** [comment]
Ah I did do that for one of them but not the other. All good, I'll do it for all future ones.

**Comment by cloudhead** [comment]
I'm supportive of this though it does give everything a rounder look. There is one issue at least while just browsing around:
image

**Comment by brandonhaslegs** [comment]
Cool, will check that out. Also if we wanna change the small radius, it's now a variable so it's wuite easy to adjust across the whole app.

**Comment by brandonhaslegs** [comment]
Where are other dropdowns in the app I can check out? I added padding all around the dropdown element instead of just the top and bottom which fixes it in this case, but i'm curious what multiple-option dropdowns look like.

**Comment by cloudhead** [comment]
There is one other dropdown in `Header.svelte` called `seedDropdown`

**Comment by cloudhead** [comment]
image

**Comment by cloudhead** [comment]
You can get the dropdown to appear if you sign-in to the `radicle.local` seed, which requires starting http-api with `RADICLE_DOMAIN=0.0.0.0`

**Comment by cloudhead** [comment]
Hmm not a fan of this look with the padding all around the selection.

**Comment by brandonhaslegs** [comment]
Cool no big deal, that's just how macOS does it. I'll remove the padding on the sides and bump the border radius down to a point where it works.

**Comment by brandonhaslegs** [comment]
So this is how I see it now. The highlighted item shouldn't be bussin out of the dropdown anymore. Does it render the same way for you?
image

**Comment by cloudhead** [comment]
Yes looks good!

**Comment by cloudhead** [comment]
> Cool no big deal, that's just how macOS does it. I'll remove the padding on the sides and bump the border radius down to a point where it works.

Is this new? last time I used macOS the selection background went to the edges.

**Comment by cloudhead** [comment]
Can you resolve the conflicts? it's CSS-related.

Also noticed this small alignment bug:
image

**Comment by cloudhead** [comment]
Ahh back in my days it looked like this:
image

**Comment by cloudhead** [comment]
> Can you resolve the conflicts? it's CSS-related.
> 
> Also noticed this small alignment bug: image
> 
> http://127.0.0.1:8080/registrations/cloudhead.eth

actually this is related to the pr I already merged it seems

**Comment by brandonhaslegs** [comment]
Yeah I will fix it in this PR though. The alignment thing I think is related to displaying buttons as `inline-flex`. But I can't find this page… http://127.0.0.1:8080/registrations/cloudhead.eth doesn't take me anywhere 🤔

**Comment by cloudhead** [comment]
> Yeah I will fix it in this PR though. The alignment thing I think is related to displaying buttons as `inline-flex`. But I can't find this page… http://127.0.0.1:8080/registrations/cloudhead.eth doesn't take me anywhere thinking

Is it because you're on rinkeby?

**Comment by cloudhead** [comment]
Another one here:

image

**Pull request merged**
