### PR TITLE
Remove Ethereum functionality

### PR DESCRIPTION
**Pull request by sebastinez**
This commit removes everything Ethereum related, this includes:
- profile pages (which relied on Ethereum information)
- testnet faucet
- vesting contract lookup
- .radicle.eth ENS registrations

Signed-off-by: Sebastian Martinez <me@sebastinez.dev>

### CODE REVIEW

**Comment by rudolfs** [comment]
🚮 🔥 

Some more stuff we can remove:
```
src/global.d.ts
    // Used in
    //   src/session.ts
    //   src/wallet.ts
    ethereum: any;
    registrarState: any;

src/lib/blockies.ts

src/components/Icon.svelte
18:    | "etherscan"
63:  {:else if name === "etherscan"}
```

**Comment by sebastinez** [comment]
> 🚮 🔥
> 
> Some more stuff we can remove:
> 
> ```
> src/global.d.ts
>     // Used in
>     //   src/session.ts
>     //   src/wallet.ts
>     ethereum: any;
>     registrarState: any;
> 
> src/lib/blockies.ts
> 
> src/components/Icon.svelte
> 18:    | "etherscan"
> 63:  {:else if name === "etherscan"}
> ```
> 
> The visual test failures are all expected. ✅

I would prefer to keep `blockies` since we use it for generation of avatars for RadicleIds.
If we want to change that, we can maybe use a different approach.

**Comment by rudolfs** [comment]
> I would prefer to keep blockies since we use it for generation of avatars for RadicleIds.

Where do we still show them in the UI?

**Review by rudolfs — APPROVED** [review]
🔥

**Pull request merged**
