### PR TITLE
Use correct tree hash for file path on diff page

### PR DESCRIPTION
**Pull request by xphoniex**
Fixes the second post of https://github.com/radicle-dev/radicle-interface/issues/925

### CODE REVIEW

**Review by sebastinez — COMMENTED** [review]
Nice catch!

I suggest a small change to make it easier to read.

```diff
diff --git a/src/views/projects/Patch.svelte b/src/views/projects/Patch.svelte
index c5af5914..04525f88 100644
--- a/src/views/projects/Patch.svelte
+++ b/src/views/projects/Patch.svelte
@@ -427,10 +427,10 @@
     </div>
     {#if currentTab === "activity"}
       {#if diff}
-        {@const revision = diff.split("..")[1]}
-        {#await api.project.getDiff(projectId, diff.split("..")[0], revision) then diff}
+        {@const [base, revision] = diff.split("..")}
+        {#await api.project.getDiff(projectId, base, revision) then { diff }}
           <div style:margin-top="1rem">
-            <Changeset {projectId} {baseUrl} {revision} diff={diff.diff} />
+            <Changeset {projectId} {baseUrl} {revision} {diff} />
           </div>
         {:catch e}
           <ErrorMessage
```

**Comment by sebastinez** [comment]
> `base, revision` part looks good, why did you change `diff={diff.diff}`?

Looks nicer and more concise. Also we only use the `diff` property of the `getDiff` output.

**Comment by xphoniex** [comment]
> 
> Looks nicer and more concise. Also we only use the `diff` property of the `getDiff` output.

[Updated](https://github.com/radicle-dev/radicle-interface/compare/9eac423b6e933830dd904228fbdd13d033104304..2be4e847a3bf31d9f4ebe1d0489cf8d6d91137f5) the `base, revision` part.

But I still don't understand the `diff` part, if I use `{diff]` it won't work, as it's not the same as `diff={diff.diff}`. Are you suggesting changing `Changeset` too?

**Comment by xphoniex** [comment]
Gotcha, missed the `{ }` part.

**Review by sebastinez — APPROVED** [review]
Nice! LGTM

**Pull request merged**
