### PR TITLE
Fix eslint error on svelte files

### PR DESCRIPTION
**Pull request by xphoniex**
30.5 seconds on **master**:
```
⮀ time npm run check

> check
> scripts/check


====================================
Loading svelte-check in workspace: /home/da/Documents/radicle-dev/radicle-interface
Getting Svelte diagnostics...

====================================
svelte-check found 0 errors and 0 warnings
Checking formatting...
All matched files use Prettier code style!

________________________________________________________
Executed in   30.52 secs    fish           external
   usr time   36.57 secs  209.00 micros   36.57 secs
   sys time    6.67 secs   82.00 micros    6.67 secs
```

9.9 seconds using this PR:
```
⮀ time npm run check

> check
> scripts/check


====================================
Loading svelte-check in workspace: /home/da/Documents/radicle-dev/radicle-interface
Getting Svelte diagnostics...

====================================
svelte-check found 0 errors and 0 warnings
Checking formatting...
All matched files use Prettier code style!

________________________________________________________
Executed in    9.90 secs    fish           external
   usr time   21.14 secs  431.00 micros   21.14 secs
   sys time    0.78 secs  165.00 micros    0.78 secs
```

### CODE REVIEW

**Review by sebastinez — COMMENTED** [review]
I'm happy with the increased speed for `npm run check`, and thanks for digging into the why @xphoniex!

But I think we can do better than prefixing the functions that return a `Promise` with `void`
I suggest either we add the eslint ignore-next-line comments, which aren't that much better, or in some cases I think we could also handle thrown errors inside a catch clause, until we get a better global error handling

**Comment by xphoniex** [comment]
> I'm happy with the increased speed for `npm run check`, and thanks for digging into the why @xphoniex!
> 
> But I think we can do better than prefixing the functions that return a `Promise` with `void` I suggest either we add the eslint ignore-next-line comments, which aren't that much better, or in some cases I think we could also handle thrown errors inside a catch clause, until we get a better global error handling

I wanted to get it working with the least amount of changes, and `void` seemed to be the solution.

```
$ TIMING=1 npx eslint .
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
@typescript-eslint/no-floating-promises |   206.729 |    62.3%
@typescript-eslint/naming-convention    |    39.795 |    12.0%
keyword-spacing                         |     8.597 |     2.6%
@typescript-eslint/no-loss-of-precision |     5.121 |     1.5%
no-implicit-globals                     |     3.904 |     1.2%
no-multi-spaces                         |     3.860 |     1.2%
no-misleading-character-class           |     3.326 |     1.0%
@typescript-eslint/no-empty-function    |     2.815 |     0.8%
no-trailing-spaces                      |     2.679 |     0.8%
no-regex-spaces                         |     2.485 |     0.7%
```

according to this, `no-floating-promises` is taking the most time to process, so perhaps we can speeds this up even more.

also there were other issues, such as "not being able to find config file" in certain paths, one can get a more detailed log with:
```
$ npx eslint . --debug
```

**Comment by sebastinez** [comment]
TIL about the `TIMING` env variable for eslint 🤩  thanks @xphoniex 
@rudolfs could we maybe revert the addition of the `no-floating-promises` rule, I don't think it adds a lot besides multiple seconds to `npm run check`.

**Comment by rudolfs** [comment]
Going to close this in favour of https://github.com/radicle-dev/radicle-interface/pull/792.

**Pull request closed without merging**
